packages:
  - apps/*
  - packages/*
  - '!**/test/**'

catalogs:
  default:
    '@faker-js/faker': ^10.2.0
    '@tailwindcss/vite': ^4.1.13
    '@types/node': ^25.0.10
    '@vitejs/plugin-vue': ^6.0.3
    pathe: ^2.0.3
    tailwindcss: ^4.1.13
    tsx: ^4.21.0
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vite: ^7.3.1
    vue: ^3.5.27
    wrangler: ^4.60.0

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - workerd
