import type { RequestHandler, RouteRule } from 'mokup'

const handler: RequestHandler = (c) => {
  const id = c.req.param('id')
  return {
    id,
    name: id === '42' ? 'Ari Park' : 'Unknown',
    detail: 'User response generated by Mokup runtime.',
  }
}

const rule: RouteRule = {
  handler,
}

export default rule
