export function buildSwRegistrationScript(importPath: string, path: string, scope: string) {
  return [
    `import { registerMokupServiceWorker } from ${JSON.stringify(importPath)}`,
    '(() => {',
    `  const registrationPromise = registerMokupServiceWorker({ path: ${JSON.stringify(path)}, scope: ${JSON.stringify(scope)} })`,
    '  const hot = import.meta.hot',
    '  if (!hot) return',
    '  let active = true',
    '  let pending = false',
    '  let running = false',
    '  let stopWatching = () => {}',
    '  let watching = false',
    '  const workers = new Set()',
    '  const watchInstallation = (registration) => {',
    '    if (!watching) {',
    '      watching = true',
    '      registration.addEventListener(\'updatefound\', update)',
    '      stopWatching = () => {',
    '        registration.removeEventListener(\'updatefound\', update)',
    '        for (const worker of workers) worker.removeEventListener(\'statechange\', update)',
    '        workers.clear()',
    '        watching = false',
    '      }',
    '    }',
    '    for (const worker of [registration.installing, registration.waiting, registration.active]) {',
    '      if (worker && !workers.has(worker)) {',
    '        workers.add(worker)',
    '        worker.addEventListener(\'statechange\', update)',
    '      }',
    '    }',
    '  }',
    '  const update = async () => {',
    '    pending = true',
    '    if (running || !active) return',
    '    running = true',
    '    try {',
    '      const registration = await registrationPromise',
    '      while (active && pending && registration) {',
    '        if (![registration.waiting, registration.active].some((worker) => worker && worker.state !== \'redundant\')) {',
    '          watchInstallation(registration)',
    '          break',
    '        }',
    '        stopWatching()',
    '        pending = false',
    '        try {',
    '          await registration.update()',
    '        } catch (error) {',
    '          console.warn(\'Failed to update mokup service worker:\', error)',
    '        }',
    '      }',
    '    } finally {',
    '      running = false',
    '    }',
    '  }',
    '  hot.on(\'mokup:routes-changed\', update)',
    '  hot.on(\'vite:ws:connect\', update)',
    '  hot.dispose(() => {',
    '    active = false',
    '    stopWatching()',
    '    hot.off(\'mokup:routes-changed\', update)',
    '    hot.off(\'vite:ws:connect\', update)',
    '  })',
    // Registration may finish after a route event, or after reconnecting to HMR.
    '  update()',
    '})()',
  ].join('\n')
}
