<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'

const hostStatus = ref('checking...')
const hostScript = ref('n/a')
const bridgeStatus = ref('waiting...')
const output = ref('{}')

function setOutput(value: unknown) {
  output.value = JSON.stringify(value, null, 2)
}

function setHostStatus(value: string) {
  hostStatus.value = value
}

function setHostScript(value: string) {
  hostScript.value = value
}

function setBridgeStatus(value: string) {
  bridgeStatus.value = value
}

async function fetchJson(url: string, init?: RequestInit) {
  const response = await fetch(url, init)
  const contentType = response.headers.get('content-type') ?? ''
  if (contentType.includes('application/json')) {
    return response.json()
  }
  return response.text()
}

function formatScriptUrl(scriptUrl: string | undefined) {
  if (!scriptUrl) {
    return 'n/a'
  }
  try {
    return new URL(scriptUrl).pathname
  }
  catch {
    return scriptUrl
  }
}

function isHostScript(scriptUrl: string | undefined) {
  if (!scriptUrl) {
    return false
  }
  try {
    return new URL(scriptUrl).pathname.endsWith('/sw.js')
  }
  catch {
    return scriptUrl.includes('sw.js')
  }
}

function getRegistrationScriptUrl(registration: ServiceWorkerRegistration) {
  return (
    registration.active?.scriptURL
    ?? registration.waiting?.scriptURL
    ?? registration.installing?.scriptURL
  )
}

async function getHostRegistration() {
  if (!('serviceWorker' in navigator)) {
    return null
  }
  const registrations = await navigator.serviceWorker.getRegistrations()
  if (registrations.length === 0) {
    return null
  }
  const preferred = registrations.find(registration =>
    isHostScript(getRegistrationScriptUrl(registration)),
  )
  return preferred ?? registrations[0] ?? null
}

async function updateHostStatus() {
  if (!('serviceWorker' in navigator)) {
    setHostStatus('not supported')
    setHostScript('n/a')
    return
  }
  const registration = await getHostRegistration()
  if (!registration) {
    setHostStatus('not registered')
    setHostScript('n/a')
    return
  }
  const scriptUrl = getRegistrationScriptUrl(registration)
  setHostScript(formatScriptUrl(scriptUrl))
  if (navigator.serviceWorker.controller) {
    setHostStatus('active')
    return
  }
  if (registration.installing || registration.waiting) {
    setHostStatus('installing')
    return
  }
  setHostStatus('installed')
}

async function ping() {
  const result = await fetchJson('/api/ping')
  setOutput(result)
}

async function echo() {
  const result = await fetchJson('/api/echo', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      ok: true,
      sentAt: new Date().toISOString(),
    }),
  })
  setOutput(result)
}

async function registerHostSw() {
  if (!('serviceWorker' in navigator)) {
    return
  }
  try {
    await navigator.serviceWorker.register('/sw.js', { scope: '/' })
  }
  catch (error) {
    setOutput({ error: String(error) })
  }
  await updateHostStatus()
}

async function updateHostSw() {
  if (!('serviceWorker' in navigator)) {
    return
  }
  const registration = await getHostRegistration()
  await registration?.update()
  await updateHostStatus()
}

async function unregisterHostSw() {
  if (!('serviceWorker' in navigator)) {
    return
  }
  const registrations = await navigator.serviceWorker.getRegistrations()
  await Promise.all(registrations.map(registration => registration.unregister()))
  setBridgeStatus('waiting...')
  await updateHostStatus()
}

function handleControllerChange() {
  void updateHostStatus()
}

function handleMessage(event: MessageEvent) {
  const data = event.data
  if (!data || typeof data !== 'object') {
    return
  }
  if (data.type === 'mokup:bridge-ready') {
    setBridgeStatus('ready')
  }
  if (data.type === 'mokup:bridge-error') {
    setBridgeStatus('error')
  }
}

onMounted(() => {
  setBridgeStatus('waiting...')
  void updateHostStatus()
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.addEventListener('controllerchange', handleControllerChange)
    navigator.serviceWorker.addEventListener('message', handleMessage)
    void navigator.serviceWorker.ready.then(() => updateHostStatus())
  }
})

onBeforeUnmount(() => {
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.removeEventListener('controllerchange', handleControllerChange)
    navigator.serviceWorker.removeEventListener('message', handleMessage)
  }
})
</script>

<template>
  <main>
    <h1>Mokup Host Service Worker Demo</h1>
    <p>
      The host SW is generated by <code>vite-plugin-pwa</code> (generateSW) and auto-registered. It imports
      <code>/mokup-sw.js</code> via a bridge script so Mokup routes work in dev and prod.
    </p>
    <div class="meta">
      <span class="pill">/api/ping</span>
      <span class="pill">/api/echo</span>
      <span class="pill secondary">Host SW: <span data-testid="host-status">{{ hostStatus }}</span></span>
      <span class="pill">Host script: <span data-testid="host-script">{{ hostScript }}</span></span>
      <span class="pill secondary">Bridge: <span data-testid="bridge-status">{{ bridgeStatus }}</span></span>
    </div>
    <div class="actions">
      <button type="button" data-testid="host-run-ping" @click="ping">
        Ping mock
      </button>
      <button type="button" class="secondary" data-testid="host-run-echo" @click="echo">
        Echo mock
      </button>
      <button type="button" data-testid="host-update-sw" @click="updateHostSw">
        Update host SW
      </button>
      <button type="button" class="secondary" data-testid="host-register-sw" @click="registerHostSw">
        Register host SW
      </button>
      <button type="button" class="secondary" data-testid="host-unregister-sw" @click="unregisterHostSw">
        Unregister host SW
      </button>
    </div>
    <pre data-testid="host-output">{{ output }}</pre>
  </main>
</template>

<style>
:root {
  color-scheme: light;
  font-family: 'Space Grotesk', 'IBM Plex Sans', ui-sans-serif, system-ui;
  background: radial-gradient(circle at 10% 10%, #f6f2ff 0%, #fef7e5 45%, #f3f9ff 100%);
  color: #1a1a1a;
}

body {
  margin: 0;
  min-height: 100vh;
  display: grid;
  place-items: center;
}

main {
  width: min(940px, 92vw);
  background: rgba(255, 255, 255, 0.75);
  border: 1px solid rgba(0, 0, 0, 0.06);
  border-radius: 28px;
  padding: 32px;
  box-shadow: 0 24px 60px rgba(31, 32, 41, 0.12);
  backdrop-filter: blur(12px);
}

h1 {
  font-size: clamp(28px, 5vw, 40px);
  margin: 0 0 8px;
}

p {
  margin: 0 0 16px;
  color: #4a4a4a;
}

.meta {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
  margin-bottom: 24px;
  font-size: 14px;
}

.pill {
  padding: 6px 12px;
  border-radius: 999px;
  background: #111;
  color: #fff;
  font-weight: 600;
}

.pill.secondary {
  background: #fff;
  color: #111;
  border: 1px solid rgba(0, 0, 0, 0.1);
}

.actions {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
  margin-bottom: 20px;
}

button {
  padding: 10px 16px;
  border-radius: 12px;
  border: none;
  font-weight: 600;
  cursor: pointer;
  background: #111;
  color: #fff;
  transition:
    transform 0.15s ease,
    box-shadow 0.15s ease;
}

button.secondary {
  background: #fff;
  color: #111;
  border: 1px solid rgba(0, 0, 0, 0.12);
}

button:hover {
  transform: translateY(-2px);
  box-shadow: 0 12px 24px rgba(17, 17, 17, 0.18);
}

pre {
  margin: 0;
  background: #0f172a;
  color: #e2e8f0;
  padding: 16px;
  border-radius: 16px;
  min-height: 180px;
  white-space: pre-wrap;
}
</style>
