function createRuntimeRuleHelpers() {
  return [
    'const resolveModuleExport = (mod) => mod?.default ?? mod',
    '',
    'const toRuntimeRule = (value) => {',
    '  if (typeof value === \'undefined\') {',
    '    return null',
    '  }',
    '  if (typeof value === \'function\') {',
    '    return { handler: value }',
    '  }',
    '  if (value === null) {',
    '    return { handler: null }',
    '  }',
    '  if (typeof value === \'object\') {',
    '    if (\'handler\' in value) {',
    '      const handlerRule = value',
    '      return {',
    '        handler: handlerRule.handler,',
    '        ...(typeof handlerRule.status === \'number\' ? { status: handlerRule.status } : {}),',
    '        ...(handlerRule.headers ? { headers: handlerRule.headers } : {}),',
    '        ...(typeof handlerRule.delay === \'number\' ? { delay: handlerRule.delay } : {}),',
    '      }',
    '    }',
    '    if (\'response\' in value) {',
    '      const responseRule = value',
    '      return {',
    '        handler: responseRule.response,',
    '        ...(typeof responseRule.status === \'number\' ? { status: responseRule.status } : {}),',
    '        ...(responseRule.headers ? { headers: responseRule.headers } : {}),',
    '        ...(typeof responseRule.delay === \'number\' ? { delay: responseRule.delay } : {}),',
    '      }',
    '    }',
    '    return { handler: value }',
    '  }',
    '  return { handler: value }',
    '}',
    '',
    'const toRuntimeRules = (value) => {',
    '  if (typeof value === \'undefined\') {',
    '    return []',
    '  }',
    '  if (Array.isArray(value)) {',
    '    return value.map(toRuntimeRule).filter(Boolean)',
    '  }',
    '  const rule = toRuntimeRule(value)',
    '  return rule ? [rule] : []',
    '}',
  ]
}

export { createRuntimeRuleHelpers }
